<a href="https://colab.research.google.com/github/martinpdab/asapa/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sklearn

In [2]:
import numpy as np
import pandas as pd

try:
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [4]:
URL = 'https://raw.githubusercontent.com/martinpdab/asapa/main/dataset.csv'
dataframe = pd.read_csv(URL)
dataframe.head()

Tempat Kejadian  ... Mitigasi Resiko
0    rumah-tangga  ...               3
1    rumah-tangga  ...               3
2    rumah-tangga  ...               3
3    rumah-tangga  ...               3
4    rumah-tangga  ...               3

[5 rows x 7 columns]

In [17]:
from sklearn.utils import shuffle
df = shuffle(dataframe)


Tempat Kejadian  ... Mitigasi Resiko
4925         lainnya  ...               2
433     rumah-tangga  ...               3
402     rumah-tangga  ...               3
4850         lainnya  ...               3
2174    rumah-tangga  ...               1

[5 rows x 7 columns]

In [20]:
df.head()

Tempat Kejadian  ... Mitigasi Resiko
4925         lainnya  ...               2
433     rumah-tangga  ...               3
402     rumah-tangga  ...               3
4850         lainnya  ...               3
2174    rumah-tangga  ...               1

[5 rows x 7 columns]

In [10]:
train, test = train_test_split(df, test_size=0.1)
print(len(train), 'train examples')
print(len(test), 'test examples')

4697 train examples
522 test examples


In [11]:
def df_to_dataset(df, shuffle=True, batch_size=32):
  dataframe = df.copy()
  labels = df.pop('Mitigasi Resiko')
  ds = tf.data.Dataset.from_tensor_slices((dict(df), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(df))
  ds = ds.batch(batch_size)
  return ds

In [12]:
batch_size = 5
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [25]:
for feature_batch, label_batch in train_ds.take(1):
  print('Parameter:', list(feature_batch.keys()))
  print('Tempat Kejadian:', feature_batch['Tempat Kejadian'])
  print('Jenis Kekerasan:', feature_batch['Jenis Kekerasan'])
  print('Banyak Kekerasan:', feature_batch['Banyak Kekerasan yang dialami'])
  print('Banyak Korban:', feature_batch['Banyak Korban Kekerasan'])
  print('Usia Korban:', feature_batch['Usia Korban'])
  print('Hubungan Pelaku dengan Korban:', feature_batch['Hubungan Pelaku dengan Korban'])
  print('Label:', label_batch )

Parameter: ['Tempat Kejadian', 'Jenis Kekerasan', 'Banyak Kekerasan yang dialami', 'Banyak Korban Kekerasan', 'Usia Korban', 'Hubungan Pelaku dengan Korban']
Tempat Kejadian: tf.Tensor(
[b'lainnya' b'rumah-tangga' b'rumah-tangga' b'rumah-tangga'
 b'rumah-tangga'], shape=(5,), dtype=string)
Jenis Kekerasan: tf.Tensor([b'seksual' b'seksual' b'seksual' b'psikis' b'psikis'], shape=(5,), dtype=string)
Banyak Kekerasan: tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int64)
Banyak Korban: tf.Tensor([1 1 1 1 1], shape=(5,), dtype=int64)
Usia Korban: tf.Tensor([b'anak-anak' b'remaja' b'dewasa' b'dewasa' b'dewasa'], shape=(5,), dtype=string)
Hubungan Pelaku dengan Korban: tf.Tensor([b'tetangga' b'orang-tua' b'pacar/teman' b'keluarga/saudara' b'majikan'], shape=(5,), dtype=string)
Label: tf.Tensor([3 3 3 1 1], shape=(5,), dtype=int64)


In [ ]:
tempat_kejadian = feature_column.categorical_column_with_vocabulary_list(
                'Tempat Kejadian', ['rumah-tangga', 'tempat-kerja', 'sekolah', 'fasilitas-umum', 'lainnya'])
thal_one_hot = feature_column.indicator_column(thal)
feature_columns.append(thal_one_hot)
