<a href="https://colab.research.google.com/github/martinpdab/asapa/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
!pip install sklearn

In [7]:
import numpy as np
import pandas as pd

try:
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

In [8]:
URL = 'https://raw.githubusercontent.com/martinpdab/asapa/main/dataset.csv'
dataframe = pd.read_csv(URL)
dataframe.head()

Tempat Kejadian  ... Mitigasi Resiko
0    rumah-tangga  ...               3
1    rumah-tangga  ...               3
2    rumah-tangga  ...               3
3    rumah-tangga  ...               3
4    rumah-tangga  ...               3

[5 rows x 7 columns]

In [9]:
from sklearn.utils import shuffle
df = shuffle(dataframe)


In [10]:
df.head()

Tempat Kejadian  ... Mitigasi Resiko
3312  fasilitas-umum  ...               2
3732  fasilitas-umum  ...               3
4850         lainnya  ...               3
186     rumah-tangga  ...               3
1279    rumah-tangga  ...               3

[5 rows x 7 columns]

In [11]:
train, test = train_test_split(df, test_size=0.1)
print(len(train), 'train examples')
print(len(test), 'test examples')

4697 train examples
522 test examples


In [12]:
def df_to_dataset(df, shuffle=True, batch_size=32):
  df = df.copy()
  labels = df.pop('Mitigasi Resiko')
  ds = tf.data.Dataset.from_tensor_slices((dict(df), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(df))
  ds = ds.batch(batch_size)
  return ds

In [14]:
batch_size = 5
train_ds = df_to_dataset(train, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

In [15]:
for feature_batch, label_batch in train_ds.take(1):
  print('Parameter:', list(feature_batch.keys()))
  print('Tempat Kejadian:', feature_batch['Tempat Kejadian'])
  print('Jenis Kekerasan:', feature_batch['Jenis Kekerasan'])
  print('Banyak Kekerasan:', feature_batch['Banyak Kekerasan yang dialami'])
  print('Banyak Korban:', feature_batch['Banyak Korban Kekerasan'])
  print('Usia Korban:', feature_batch['Usia Korban'])
  print('Hubungan Pelaku dengan Korban:', feature_batch['Hubungan Pelaku dengan Korban'])
  print('Label:', label_batch )

Parameter: ['Tempat Kejadian', 'Jenis Kekerasan', 'Banyak Kekerasan yang dialami', 'Banyak Korban Kekerasan', 'Usia Korban', 'Hubungan Pelaku dengan Korban']
Tempat Kejadian: tf.Tensor([b'rumah-tangga' b'lainnya' b'rumah-tangga' b'lainnya' b'lainnya'], shape=(5,), dtype=string)
Jenis Kekerasan: tf.Tensor([b'lainnya' b'psikis' b'seksual' b'fisik' b'fisik'], shape=(5,), dtype=string)
Banyak Kekerasan: tf.Tensor([1 1 1 1 2], shape=(5,), dtype=int64)
Banyak Korban: tf.Tensor([1 1 1 2 1], shape=(5,), dtype=int64)
Usia Korban: tf.Tensor([b'anak-anak' b'dewasa' b'dewasa' b'anak-anak' b'lansia'], shape=(5,), dtype=string)
Hubungan Pelaku dengan Korban: tf.Tensor([b'orang-tua' b'pacar/teman' b'suami/istri' b'lainnya' b'keluarga/saudara'], shape=(5,), dtype=string)
Label: tf.Tensor([2 2 1 3 3], shape=(5,), dtype=int64)


In [18]:
feature_column = []
tempat_kejadian = feature_column.categorical_column_with_vocabulary_list(
                'Tempat Kejadian', ['rumah-tangga', 'tempat-kerja', 'sekolah', 'fasilitas-umum', 'lainnya'])
tempat_one_hot = feature_column.indicator_column(tempat_kejadian)
feature_columns.append(tempat_one_hot)


AttributeError: ignored